// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	product "ricitelli-back/internal/domain/product"
	production_order "ricitelli-back/internal/domain/production-order"
	sale_order "ricitelli-back/internal/domain/sale-order"
	entities "ricitelli-back/internal/entities"
	value_object "ricitelli-back/internal/value-object"

	gomock "github.com/golang/mock/gomock"
)

// MockProductService is a mock of ProductService interface.
type MockProductService struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceMockRecorder
}

// MockProductServiceMockRecorder is the mock recorder for MockProductService.
type MockProductServiceMockRecorder struct {
	mock *MockProductService
}

// NewMockProductService creates a new mock instance.
func NewMockProductService(ctrl *gomock.Controller) *MockProductService {
	mock := &MockProductService{ctrl: ctrl}
	mock.recorder = &MockProductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductService) EXPECT() *MockProductServiceMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockProductService) CreateProduct(ctx context.Context, name string, bods []value_object.BillOfDrySupply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, name, bods)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductServiceMockRecorder) CreateProduct(ctx, name, bods interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductService)(nil).CreateProduct), ctx, name, bods)
}

// GetProductByID mocks base method.
func (m *MockProductService) GetProductByID(ctx context.Context, id string) (*product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, id)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockProductServiceMockRecorder) GetProductByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockProductService)(nil).GetProductByID), ctx, id)
}

// GetProducts mocks base method.
func (m *MockProductService) GetProducts(ctx context.Context) ([]product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProducts", ctx)
	ret0, _ := ret[0].([]product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProducts indicates an expected call of GetProducts.
func (mr *MockProductServiceMockRecorder) GetProducts(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProducts", reflect.TypeOf((*MockProductService)(nil).GetProducts), ctx)
}

// UpdateProduct mocks base method.
func (m *MockProductService) UpdateProduct(ctx context.Context, id, name string, bods []value_object.BillOfDrySupply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, id, name, bods)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductServiceMockRecorder) UpdateProduct(ctx, id, name, bods interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductService)(nil).UpdateProduct), ctx, id, name, bods)
}

// SetProductImage mocks base method.
func (m *MockProductService) SetProductImage(ctx context.Context, id, imageURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProductImage", ctx, id, imageURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProductImage indicates an expected call of SetProductImage.
func (mr *MockProductServiceMockRecorder) SetProductImage(ctx, id, imageURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProductImage", reflect.TypeOf((*MockProductService)(nil).SetProductImage), ctx, id, imageURL)
}

// GetProductImage mocks base method.
func (m *MockProductService) GetProductImage(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductImage", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductImage indicates an expected call of GetProductImage.
func (mr *MockProductServiceMockRecorder) GetProductImage(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductImage", reflect.TypeOf((*MockProductService)(nil).GetProductImage), ctx, id)
}

// MockSaleOrderService is a mock of SaleOrderService interface.
type MockSaleOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockSaleOrderServiceMockRecorder
}

// MockSaleOrderServiceMockRecorder is the mock recorder for MockSaleOrderService.
type MockSaleOrderServiceMockRecorder struct {
	mock *MockSaleOrderService
}

// NewMockSaleOrderService creates a new mock instance.
func NewMockSaleOrderService(ctrl *gomock.Controller) *MockSaleOrderService {
	mock := &MockSaleOrderService{ctrl: ctrl}
	mock.recorder = &MockSaleOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaleOrderService) EXPECT() *MockSaleOrderServiceMockRecorder {
	return m.recorder
}

// CreateSaleOrder mocks base method.
func (m *MockSaleOrderService) CreateSaleOrder(ctx context.Context, customerID string, items []value_object.SaleOrderItem) (sale_order.SaleOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSaleOrder", ctx, customerID, items)
	ret0, _ := ret[0].(sale_order.SaleOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSaleOrder indicates an expected call of CreateSaleOrder.
func (mr *MockSaleOrderServiceMockRecorder) CreateSaleOrder(ctx, customerID, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSaleOrder", reflect.TypeOf((*MockSaleOrderService)(nil).CreateSaleOrder), ctx, customerID, items)
}

// GetSaleOrderByID mocks base method.
func (m *MockSaleOrderService) GetSaleOrderByID(ctx context.Context, id string) (*sale_order.SaleOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSaleOrderByID", ctx, id)
	ret0, _ := ret[0].(*sale_order.SaleOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSaleOrderByID indicates an expected call of GetSaleOrderByID.
func (mr *MockSaleOrderServiceMockRecorder) GetSaleOrderByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSaleOrderByID", reflect.TypeOf((*MockSaleOrderService)(nil).GetSaleOrderByID), ctx, id)
}

// GetSaleOrders mocks base method.
func (m *MockSaleOrderService) GetSaleOrders(ctx context.Context) ([]sale_order.SaleOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSaleOrders", ctx)
	ret0, _ := ret[0].([]sale_order.SaleOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSaleOrders indicates an expected call of GetSaleOrders.
func (mr *MockSaleOrderServiceMockRecorder) GetSaleOrders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSaleOrders", reflect.TypeOf((*MockSaleOrderService)(nil).GetSaleOrders), ctx)
}

// MockProductionOrderService is a mock of ProductionOrderService interface.
type MockProductionOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockProductionOrderServiceMockRecorder
}

// MockProductionOrderServiceMockRecorder is the mock recorder for MockProductionOrderService.
type MockProductionOrderServiceMockRecorder struct {
	mock *MockProductionOrderService
}

// NewMockProductionOrderService creates a new mock instance.
func NewMockProductionOrderService(ctrl *gomock.Controller) *MockProductionOrderService {
	mock := &MockProductionOrderService{ctrl: ctrl}
	mock.recorder = &MockProductionOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductionOrderService) EXPECT() *MockProductionOrderServiceMockRecorder {
	return m.recorder
}

// CreateProductionOrder mocks base method.
func (m *MockProductionOrderService) CreateProductionOrder(ctx context.Context, salesOrderID string, items []entities.ProductionItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductionOrder", ctx, salesOrderID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProductionOrder indicates an expected call of CreateProductionOrder.
func (mr *MockProductionOrderServiceMockRecorder) CreateProductionOrder(ctx, salesOrderID, items interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductionOrder", reflect.TypeOf((*MockProductionOrderService)(nil).CreateProductionOrder), ctx, salesOrderID, items)
}

// GetProductionOrderByID mocks base method.
func (m *MockProductionOrderService) GetProductionOrderByID(ctx context.Context, id string) (*production_order.ProductionOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductionOrderByID", ctx, id)
	ret0, _ := ret[0].(*production_order.ProductionOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductionOrderByID indicates an expected call of GetProductionOrderByID.
func (mr *MockProductionOrderServiceMockRecorder) GetProductionOrderByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductionOrderByID", reflect.TypeOf((*MockProductionOrderService)(nil).GetProductionOrderByID), ctx, id)
}

// GetProductionOrders mocks base method.
func (m *MockProductionOrderService) GetProductionOrders(ctx context.Context) ([]production_order.ProductionOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductionOrders", ctx)
	ret0, _ := ret[0].([]production_order.ProductionOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductionOrders indicates an expected call of GetProductionOrders.
func (mr *MockProductionOrderServiceMockRecorder) GetProductionOrders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductionOrders", reflect.TypeOf((*MockProductionOrderService)(nil).GetProductionOrders), ctx)
}
